
- name: roles.developer.tasks.apt
  ansible.builtin.debug:
    msg:
    - "applying tasks under roles.developer.tasks.apt"
- name: Install apt packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
  vars:
    packages:
    - python3-dev
    - python3-pip