---
repos:
    # Mandatory hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-json
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          #- id: no-commit-to-branch # both main and master protected by default
          - id: detect-private-key
          - id: detect-aws-credentials
            args:
                - --allow-missing-credentials
    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.15.3
      hooks:
          - id: gitleaks
# Repository/tech specific hooks
    - repo: https://github.com/ansible/ansible-lint.git
      rev: v6.14.0a0
      hooks:
          - id: ansible-lint
            files: \.(yaml|yml)$
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v2.1.1
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            args: [feat, fix, ci, chore, test]
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.2
      hooks:
          - id: shellcheck
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.33.0
      hooks:
          - id: markdownlint
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
          - id: validate-toml
