---
- name: roles.common.tasks.apt
  ansible.builtin.debug:
    msg:
    - "applying tasks under roles.common.tasks.apt"

- name: Add official KeePassXC repository
  apt_repository:
    repo: ppa:phoerious/keepassxc

- name: Install apt packages
  apt:
    name: "{{ packages }}"
    force_apt_get: yes
  vars:
    packages:
    - elinks
    - snapd

- name: Set default editor to vim
  alternatives:
    name: editor
    path: /usr/bin/vim.basic


